### ISSUE TITLE
Error while wmt-makedb slopes import - 'WKBWriter' object has no attribute 'srid'

### ISSUE THREAD

**Issue by doubotis** [waymarkedtrails/waymarkedtrails-backend#14]
Hello !

I followed all docs to import and build the schemas but I got an error when I try to use the command `wmt-makedb slopes import`.

It throws at `way_relations` table step with the following exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wmtenv/lib/python3.7/site-packages/osgende/common/threads.py", line 53, in worker_loop
    process_func(req)
  File "/home/wmtenv/lib/python3.7/site-packages/osgende/lines/relation_ways.py", line 319, in _process_construct_next
    cols = self._construct_row(obj, self.thread.conn)
  File "/home/wmtenv/lib/python3.7/site-packages/osgende/lines/relation_ways.py", line 340, in _construct_row
    cols['geom'] = from_shape(new_geom, srid=self.srid)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.7/site-packages/geoalchemy2/shape.py", line 84, in from_shape
    memoryview(dumps(shape, srid=srid if extended else None)),
  File "/usr/lib/python3/dist-packages/shapely/wkb.py", line 28, in dumps
    writer = geos.WKBWriter(geos.lgeos, **kw)
  File "/usr/lib/python3/dist-packages/shapely/geos.py", line 466, in __init__
    setattr(self, name, applied_settings[name])
  File "/usr/lib/python3/dist-packages/shapely/geos.py", line 474, in __setattr__
    (self.__class__.__name__, name))
AttributeError: 'WKBWriter' object has no attribute 'srid'
```

I got the same errors for all schemas. I got same issues with `mtb` or `hiking` for instance.

Do you have an idea of the issue here? Maybe I forgot something?

**Comment by lonvia** [comment]
This looks like your version of shapely is too old. I'm also fairly sure that Python 3.7 won't work. The instructions are outdated there. The production server runs on Debian 12. Any chance you can use that as a base? I'll update the README.

**Comment by doubotis** [comment]
Hello !

Thanks for your quick response!

I'am on Debian 10 (2019) and the python3-shapely package from package manager was veeeery old.
I upgraded to last Shapely version, still compatible with Python 3.7.

I retried after the upgrade and the import seems to work well.
If something else goes wrong I'll update the environment to Debian 12.

Thanks for the answer and updating the README ^_^ 👍
