### ISSUE TITLE
name 'cai_level' is not defined

### ISSUE THREAD

**Issue by hholzgra** [waymarkedtrails/waymarkedtrails-backend#2]
looks as if the dynamic import approach makes global symbols from the config/*.py files not end up in the global scope?

```
20-06-28 17:01:14 Importing routes...
20-06-28 17:01:14 Using 1 parallel threads.
20-06-28 17:01:16 Using 1 parallel threads.
20-06-28 17:01:22 Using 1 parallel threads.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/osgende/common/threads.py", line 143, in loop
    self.process_func(req)
  File "/home/maposmatic/styles/waymarkedtrails-backend/db/tables/routes.py", line 200, in _process_construct_next
    cols = self._construct_row(obj, self.thread.conn)
  File "/home/maposmatic/styles/waymarkedtrails-backend/db/tables/routes.py", line 288, in _construct_row
    self.config.tag_filter(outtags, tags)
  File "/home/maposmatic/styles/waymarkedtrails-backend/config/hiking.py", line 51, in filter_route_tags
    outtags.network = 'AL' + cai_level.get(tags['cai_scale'], '4')
NameError: name 'cai_level' is not defined
20-06-28 17:01:24 Internal error. Thread died. Killing other threads.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/osgende/common/threads.py", line 73, in add_task
    self.queue.put(data, True, 2)
  File "/usr/lib/python3.8/queue.py", line 147, in put
    raise Full
queue.Full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./makedb.py", line 210, in <module>
    exit(action())
  File "./makedb.py", line 104, in construct
    self.mapdb.construct()
  File "/usr/local/lib/python3.8/dist-packages/osgende/mapdb.py", line 91, in construct
    tab.construct(self.engine)
  File "/home/maposmatic/styles/waymarkedtrails-backend/db/tables/routes.py", line 150, in construct
    self.insert_objects(engine, subset)
  File "/home/maposmatic/styles/waymarkedtrails-backend/db/tables/routes.py", line 194, in insert_objects
    workers.add_task(obj)
  File "/usr/local/lib/python3.8/dist-packages/osgende/common/threads.py", line 81, in add_task
    raise Exception("Internal error. Thread died.")
Exception: Internal error. Thread died.
```

**Comment by lonvia** [comment]
I cannot reproduce this locally. I wonder if this is a new issue in Python 3.8. I'm still running 3.7.

**Comment by hholzgra** [comment]
Can't reproduce this anymore either ...
